# Generated by Django 6.0.6 on 2026-06-22 10:42

import api.models.catalog
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class CreateModelIfNotExists(migrations.CreateModel):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.name)
        if model._meta.db_table in schema_editor.connection.introspection.table_names():
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class AddIndexIfNotExists(migrations.AddIndex):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        constraints = schema_editor.connection.introspection.get_constraints(schema_editor.connection.cursor(), model._meta.db_table)
        if self.index.name in constraints:
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class AddConstraintIfNotExists(migrations.AddConstraint):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        constraints = schema_editor.connection.introspection.get_constraints(schema_editor.connection.cursor(), model._meta.db_table)
        if self.constraint.name in constraints:
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        CreateModelIfNotExists(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(blank=True, max_length=170, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="api.productcategory",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        CreateModelIfNotExists(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_id",
                    models.CharField(editable=False, max_length=30, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=280)),
                ("short_description", models.CharField(blank=True, max_length=500)),
                ("description", models.TextField(blank=True)),
                ("sku", models.CharField(blank=True, max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "compare_at_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("currency", models.CharField(default="TZS", max_length=10)),
                ("stock_quantity", models.PositiveIntegerField(default=0)),
                ("minimum_order_quantity", models.PositiveIntegerField(default=1)),
                ("unit", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_review", "Pending review"),
                            ("active", "Active"),
                            ("rejected", "Rejected"),
                            ("out_of_stock", "Out of stock"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_discountable", models.BooleanField(default=True)),
                ("position", models.PositiveIntegerField(blank=True, null=True)),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("sold_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="api.traderbranch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_products",
                    models.ManyToManyField(
                        blank=True, related_name="related_to", to="api.product"
                    ),
                ),
                (
                    "trader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="api.traderprofile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="api.productcategory",
                    ),
                ),
            ],
            options={
                "ordering": ("position", "-created_at"),
                "permissions": [
                    ("approve_product", "Can approve product"),
                    ("feature_product", "Can feature product"),
                    ("archive_product", "Can archive product"),
                ],
            },
        ),
        CreateModelIfNotExists(
            name="ProductMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("clip", "Clip")], max_length=10
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=api.models.catalog.product_media_upload_path
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                ("is_primary", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_product_media",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="api.product",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "created_at"),
            },
        ),
        AddIndexIfNotExists(
            model_name="product",
            index=models.Index(
                fields=["trader", "status"], name="api_product_trader__b05309_idx"
            ),
        ),
        AddIndexIfNotExists(
            model_name="product",
            index=models.Index(
                fields=["category", "status"], name="api_product_categor_ff2e3e_idx"
            ),
        ),
        AddIndexIfNotExists(
            model_name="product",
            index=models.Index(
                fields=["product_id"], name="api_product_product_aec78f_idx"
            ),
        ),
        AddIndexIfNotExists(
            model_name="product",
            index=models.Index(fields=["slug"], name="api_product_slug_e70af7_idx"),
        ),
        AddIndexIfNotExists(
            model_name="product",
            index=models.Index(
                fields=["position"], name="api_product_positio_ea9f52_idx"
            ),
        ),
        AddConstraintIfNotExists(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("trader", "slug"), name="unique_product_slug_per_trader"
            ),
        ),
        AddConstraintIfNotExists(
            model_name="product",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sku", ""), _negated=True),
                fields=("trader", "sku"),
                name="unique_product_sku_per_trader",
            ),
        ),
        AddConstraintIfNotExists(
            model_name="productmedia",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("product",),
                name="one_primary_media_per_product",
            ),
        ),
    ]
