# Generated by Django 6.0.6 on 2026-07-08 11:29

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class CreateModelIfNotExists(migrations.CreateModel):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.name)
        if model._meta.db_table in schema_editor.connection.introspection.table_names():
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class AddIndexIfNotExists(migrations.AddIndex):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        constraints = schema_editor.connection.introspection.get_constraints(schema_editor.connection.cursor(), model._meta.db_table)
        if self.index.name in constraints:
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_traderprofile_trader_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        CreateModelIfNotExists(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("customer_username", models.CharField(blank=True, max_length=150)),
                ("customer_full_name", models.CharField(max_length=255)),
                ("customer_phone", models.CharField(max_length=50)),
                ("customer_email", models.EmailField(blank=True, max_length=254)),
                (
                    "customer_country",
                    models.CharField(default="Tanzania", max_length=100),
                ),
                ("customer_region", models.CharField(blank=True, max_length=100)),
                ("customer_district", models.CharField(blank=True, max_length=100)),
                ("customer_ward", models.CharField(blank=True, max_length=100)),
                ("customer_street", models.CharField(blank=True, max_length=100)),
                ("customer_address", models.TextField(blank=True)),
                ("delivery_note", models.TextField(blank=True)),
                ("admin_note", models.TextField(blank=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("web_pwa", "Web PWA"),
                            ("mobile_pwa", "Mobile PWA"),
                            ("api", "API"),
                        ],
                        default="admin",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("requested", "Requested"),
                            ("confirmed", "Confirmed"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                            ("rejected", "Rejected"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("refunded", "Refunded"),
                        ],
                        default="unpaid",
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(default="TZS", max_length=10)),
                (
                    "subtotal_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "delivery_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                ("items_count", models.PositiveIntegerField(default=0)),
                (
                    "requested_ip_address",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                ("requested_user_agent", models.TextField(blank=True)),
                ("requested_device", models.CharField(blank=True, max_length=100)),
                ("requested_browser", models.CharField(blank=True, max_length=100)),
                ("requested_os", models.CharField(blank=True, max_length=100)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "permissions": [
                    ("confirm_order", "Can confirm order"),
                    ("cancel_order", "Can cancel order"),
                    ("mark_order_delivered", "Can mark order delivered"),
                ],
            },
        ),
        CreateModelIfNotExists(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_media_url", models.URLField(blank=True)),
                ("product_id_snapshot", models.CharField(blank=True, max_length=50)),
                ("product_name_snapshot", models.CharField(max_length=255)),
                ("product_sku_snapshot", models.CharField(blank=True, max_length=100)),
                ("trader_name_snapshot", models.CharField(blank=True, max_length=255)),
                ("branch_name_snapshot", models.CharField(blank=True, max_length=255)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "line_discount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.traderbranch",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="api.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items",
                        to="api.product",
                    ),
                ),
                (
                    "trader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.traderprofile",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        CreateModelIfNotExists(
            name="OrderStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=20)),
                ("to_status", models.CharField(max_length=20)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="api.order",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Order status histories",
                "ordering": ("-created_at",),
            },
        ),
        CreateModelIfNotExists(
            name="SystemRequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("username_snapshot", models.CharField(blank=True, max_length=150)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("device_type", models.CharField(blank=True, max_length=50)),
                ("browser", models.CharField(blank=True, max_length=100)),
                ("os", models.CharField(blank=True, max_length=100)),
                ("method", models.CharField(max_length=10)),
                ("path", models.CharField(max_length=500)),
                ("query_string", models.TextField(blank=True)),
                ("view_name", models.CharField(blank=True, max_length=255)),
                ("status_code", models.PositiveIntegerField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("referer", models.TextField(blank=True)),
                ("origin", models.TextField(blank=True)),
                ("is_error", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="system_request_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        CreateModelIfNotExists(
            name="UserActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username_snapshot", models.CharField(blank=True, max_length=150)),
                ("session_key", models.CharField(blank=True, max_length=100)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("device_type", models.CharField(blank=True, max_length=50)),
                ("browser", models.CharField(blank=True, max_length=100)),
                ("os", models.CharField(blank=True, max_length=100)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("product_view", "Product view"),
                            ("product_open", "Product open"),
                            ("media_view", "Media view"),
                            ("media_play", "Media play"),
                            ("media_pause", "Media pause"),
                            ("media_complete", "Media complete"),
                            ("image_zoom", "Image zoom"),
                            ("like", "Like"),
                            ("unlike", "Unlike"),
                            ("bookmark", "Bookmark"),
                            ("unbookmark", "Unbookmark"),
                            ("add_to_cart", "Add to cart"),
                            ("remove_from_cart", "Remove from cart"),
                            ("cart_quantity_change", "Cart quantity change"),
                            ("rating", "Rating"),
                            ("review", "Review"),
                            ("share", "Share"),
                            ("search", "Search"),
                            ("filter", "Filter"),
                            ("category_open", "Category open"),
                            ("trader_open", "Trader open"),
                            ("order_request", "Order request"),
                            ("order_submit", "Order submit"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "rating_value",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("search_query", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to="api.product",
                    ),
                ),
                (
                    "product_media",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to="api.productmedia",
                    ),
                ),
                (
                    "trader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to="api.traderprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        CreateModelIfNotExists(
            name="AdminActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor_username", models.CharField(blank=True, max_length=150)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("device_type", models.CharField(blank=True, max_length=50)),
                ("browser", models.CharField(blank=True, max_length=100)),
                ("os", models.CharField(blank=True, max_length=100)),
                ("module", models.CharField(max_length=50)),
                ("action", models.CharField(max_length=50)),
                ("object_type", models.CharField(blank=True, max_length=100)),
                ("object_id", models.CharField(blank=True, max_length=100)),
                ("object_repr", models.CharField(blank=True, max_length=255)),
                ("path", models.CharField(blank=True, max_length=500)),
                ("method", models.CharField(blank=True, max_length=10)),
                ("status_code", models.PositiveIntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["actor", "created_at"],
                        name="api_adminac_actor_i_da3f4e_idx",
                    ),
                    models.Index(
                        fields=["module", "action"],
                        name="api_adminac_module_52eda3_idx",
                    ),
                    models.Index(
                        fields=["object_type", "object_id"],
                        name="api_adminac_object__8752bb_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="api_adminac_created_416c3a_idx"
                    ),
                ],
            },
        ),
        AddIndexIfNotExists(
            model_name="order",
            index=models.Index(
                fields=["order_number"], name="api_order_order_n_ec9cdb_idx"
            ),
        ),
        AddIndexIfNotExists(
            model_name="order",
            index=models.Index(fields=["status"], name="api_order_status_dee4b6_idx"),
        ),
        AddIndexIfNotExists(
            model_name="order",
            index=models.Index(
                fields=["customer_phone"], name="api_order_custome_f2efdd_idx"
            ),
        ),
        AddIndexIfNotExists(
            model_name="order",
            index=models.Index(
                fields=["customer_email"], name="api_order_custome_996098_idx"
            ),
        ),
        AddIndexIfNotExists(
            model_name="order",
            index=models.Index(
                fields=["created_at"], name="api_order_created_7fb22c_idx"
            ),
        ),
        AddIndexIfNotExists(
            model_name="order",
            index=models.Index(fields=["source"], name="api_order_source_8b06e1_idx"),
        ),
        AddIndexIfNotExists(
            model_name="systemrequestlog",
            index=models.Index(
                fields=["created_at"], name="api_systemr_created_878dec_idx"
            ),
        ),
        AddIndexIfNotExists(
            model_name="systemrequestlog",
            index=models.Index(fields=["path"], name="api_systemr_path_30369d_idx"),
        ),
        AddIndexIfNotExists(
            model_name="systemrequestlog",
            index=models.Index(
                fields=["status_code"], name="api_systemr_status__0ce39c_idx"
            ),
        ),
        AddIndexIfNotExists(
            model_name="systemrequestlog",
            index=models.Index(
                fields=["is_error"], name="api_systemr_is_erro_2459a4_idx"
            ),
        ),
        AddIndexIfNotExists(
            model_name="systemrequestlog",
            index=models.Index(
                fields=["user", "created_at"], name="api_systemr_user_id_6b458f_idx"
            ),
        ),
        AddIndexIfNotExists(
            model_name="useractivitylog",
            index=models.Index(fields=["action"], name="api_useract_action_3c0624_idx"),
        ),
        migrations.AddIndex(
            model_name="useractivitylog",
            index=models.Index(
                fields=["product", "action"], name="api_useract_product_31fec0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivitylog",
            index=models.Index(
                fields=["user", "created_at"], name="api_useract_user_id_18a164_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivitylog",
            index=models.Index(
                fields=["ip_address"], name="api_useract_ip_addr_f30365_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivitylog",
            index=models.Index(
                fields=["created_at"], name="api_useract_created_80e6c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivitylog",
            index=models.Index(
                fields=["trader", "action"], name="api_useract_trader__541d87_idx"
            ),
        ),
    ]
