# Generated by Django 6.0.6 on 2026-07-22 18:47

from django.db import migrations, models


class CreateModelIfNotExists(migrations.CreateModel):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.name)
        if model._meta.db_table in schema_editor.connection.introspection.table_names():
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class AddFieldIfNotExists(migrations.AddField):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        columns = {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(schema_editor.connection.cursor(), model._meta.db_table)
        }
        if self.name in columns:
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


def backfill_order_counts_and_sequences(apps, schema_editor):
    Order = apps.get_model("api", "Order")
    OrderItem = apps.get_model("api", "OrderItem")
    OrderNumberSequence = apps.get_model("api", "OrderNumberSequence")

    sequence_by_year = {}
    for order in Order.objects.all().iterator():
        items = list(OrderItem.objects.filter(order_id=order.pk).values("quantity"))
        order.items_count = len(items)
        order.total_quantity = sum(item["quantity"] for item in items)
        order.save(update_fields=["items_count", "total_quantity"])
        try:
            _, year, number = order.order_number.split("-")
            sequence_by_year[int(year)] = max(sequence_by_year.get(int(year), 0), int(number))
        except (AttributeError, TypeError, ValueError):
            continue

    for year, last_number in sequence_by_year.items():
        OrderNumberSequence.objects.update_or_create(year=year, defaults={"last_number": last_number})


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_order_orderitem_orderstatushistory_systemrequestlog_and_more"),
    ]

    operations = [
        CreateModelIfNotExists(
            name="OrderNumberSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(unique=True)),
                ("last_number", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-year",),
            },
        ),
        AddFieldIfNotExists(
            model_name="order",
            name="total_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill_order_counts_and_sequences, migrations.RunPython.noop),
    ]
