# Generated by Django 6.0.6 on 2026-07-29 21:49

import api.models.catalog
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_ordernumbersequence_order_total_quantity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productcategory",
            options={"ordering": ("display_order", "name")},
        ),
        migrations.AddField(
            model_name="orderitem",
            name="delivery_fee_snapshot",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="selected_specifications_snapshot",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="product",
            name="delivery_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="has_selectable_specifications",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="specifications",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="product",
            name="view_360_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="view_360_mode",
            field=models.CharField(
                choices=[("spin", "360 image spin"), ("model", "3D model")],
                default="spin",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="display_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="icon",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="categories/images/"
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="productmedia",
            name="caption",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="productmedia",
            name="edit_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="productmedia",
            name="file_size",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productmedia",
            name="frame_index",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productmedia",
            name="mime_type",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="productmedia",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("image", "Image"),
                    ("clip", "Clip"),
                    ("spin_frame", "360 frame"),
                    ("model_3d", "3D model"),
                    ("poster", "Poster image"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="useractivitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("product_view", "Product view"),
                    ("product_open", "Product open"),
                    ("media_view", "Media view"),
                    ("media_play", "Media play"),
                    ("media_pause", "Media pause"),
                    ("media_complete", "Media complete"),
                    ("image_zoom", "Image zoom"),
                    ("like", "Like"),
                    ("unlike", "Unlike"),
                    ("bookmark", "Bookmark"),
                    ("unbookmark", "Unbookmark"),
                    ("add_to_cart", "Add to cart"),
                    ("remove_from_cart", "Remove from cart"),
                    ("cart_quantity_change", "Cart quantity change"),
                    ("rating", "Rating"),
                    ("review", "Review"),
                    ("share", "Share"),
                    ("search", "Search"),
                    ("filter", "Filter"),
                    ("category_open", "Category open"),
                    ("trader_open", "Trader open"),
                    ("store_follow", "Store follow"),
                    ("store_unfollow", "Store unfollow"),
                    ("order_request", "Order request"),
                    ("order_submit", "Order submit"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="BrandStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media",
                    models.FileField(
                        upload_to=api.models.catalog.brand_status_upload_path
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")], max_length=10
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=500)),
                (
                    "display_duration_seconds",
                    models.PositiveIntegerField(
                        default=15,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3600),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("starts_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_brand_statuses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "starts_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="BrandStatusView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anonymous_viewer_id",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("first_viewed_at", models.DateTimeField(auto_now_add=True)),
                ("last_viewed_at", models.DateTimeField(auto_now=True)),
                ("view_count", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="api.brandstatus",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_status_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-last_viewed_at",),
            },
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                ("selected_specifications", models.JSONField(blank=True, default=list)),
                (
                    "specification_signature",
                    models.CharField(default="none", max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="api.cart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="api.product",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(editable=False, max_length=24, unique=True),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("proforma", "Pro forma"),
                            ("order_invoice", "Order invoice"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("issued", "Issued"),
                            ("paid", "Paid"),
                            ("void", "Void"),
                        ],
                        default="issued",
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(default="TZS", max_length=10)),
                (
                    "subtotal_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "delivery_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                ("customer_name_snapshot", models.CharField(max_length=255)),
                (
                    "customer_email_snapshot",
                    models.EmailField(blank=True, max_length=254),
                ),
                (
                    "customer_phone_snapshot",
                    models.CharField(blank=True, max_length=50),
                ),
                ("customer_address_snapshot", models.TextField(blank=True)),
                (
                    "company_name_snapshot",
                    models.CharField(default="SmartWear", max_length=255),
                ),
                ("company_logo_url_snapshot", models.URLField(blank=True)),
                (
                    "cart_fingerprint",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("issued_at", models.DateTimeField()),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("void_reason", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice",
                        to="api.order",
                    ),
                ),
            ],
            options={
                "ordering": ("-issued_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id_snapshot", models.CharField(blank=True, max_length=50)),
                ("product_name_snapshot", models.CharField(max_length=255)),
                ("product_sku_snapshot", models.CharField(blank=True, max_length=100)),
                ("product_media_url", models.URLField(blank=True)),
                ("trader_name_snapshot", models.CharField(blank=True, max_length=255)),
                (
                    "selected_specifications_snapshot",
                    models.JSONField(blank=True, default=list),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "line_discount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=14)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="api.invoice",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_items",
                        to="api.product",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="InvoiceNumberSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("proforma", "Pro forma"),
                            ("order_invoice", "Order invoice"),
                        ],
                        max_length=20,
                    ),
                ),
                ("last_number", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("year", "document_type"),
                        name="unique_invoice_sequence_per_year_type",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OrderChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("open", "Open"),
                            ("closed", "Closed"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField()),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("close_reason", models.CharField(blank=True, max_length=500)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_order_chats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="closed_order_chats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_chats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opened_order_chats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat",
                        to="api.order",
                    ),
                ),
            ],
            options={
                "ordering": ("-last_message_at", "-requested_at", "-id"),
                "permissions": [("close_orderchat", "Can close order chat")],
            },
        ),
        migrations.CreateModel(
            name="OrderChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender_role",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("admin", "Admin"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("body", models.TextField(max_length=2000)),
                ("client_message_id", models.UUIDField(default=uuid.uuid4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="api.orderchat",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="OrderChatParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("customer", "Customer"), ("admin", "Admin")],
                        max_length=20,
                    ),
                ),
                ("last_read_at", models.DateTimeField(blank=True, null=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="api.orderchat",
                    ),
                ),
                (
                    "last_read_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="api.orderchatmessage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_chat_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductBookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="api.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ProductSpecificationGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "selection_mode",
                    models.CharField(
                        choices=[("single", "Single"), ("multiple", "Multiple")],
                        default="single",
                        max_length=10,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specification_groups",
                        to="api.product",
                    ),
                ),
            ],
            options={
                "ordering": ("display_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProductSpecificationOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=150)),
                (
                    "price_adjustment",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="api.productspecificationgroup",
                    ),
                ),
            ],
            options={
                "ordering": ("display_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="SiteBranding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(default="SmartWear", max_length=120)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=api.models.catalog.site_logo_upload_path,
                    ),
                ),
                ("logo_alt_text", models.CharField(blank=True, max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_site_branding",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Site branding",
                "verbose_name_plural": "Site branding",
            },
        ),
        migrations.CreateModel(
            name="StoreFollow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to="api.traderprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_follows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="UserNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("order", "Order"),
                            ("my_list", "My List"),
                            ("cart", "Cart"),
                            ("store", "Store"),
                            ("like", "Like"),
                            ("review", "Review"),
                            ("system", "System"),
                            ("chat", "Chat"),
                            ("invoice", "Invoice"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField(blank=True)),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[("pending", "Pending"), ("completed", "Completed")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activity_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="api.useractivitylog",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="api.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="api.product",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="api.traderprofile",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="brandstatus",
            index=models.Index(
                fields=["is_active", "starts_at", "expires_at"],
                name="api_brandst_is_acti_d44226_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="brandstatus",
            index=models.Index(
                fields=["sort_order", "starts_at"],
                name="api_brandst_sort_or_57195c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="brandstatusview",
            index=models.Index(
                fields=["status", "last_viewed_at"],
                name="api_brandst_status__8d4eb8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="brandstatusview",
            index=models.Index(
                fields=["user", "last_viewed_at"], name="api_brandst_user_id_8cf239_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="brandstatusview",
            index=models.Index(
                fields=["anonymous_viewer_id", "last_viewed_at"],
                name="api_brandst_anonymo_c9ec95_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="brandstatusview",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("status", "user"),
                name="unique_brand_status_user_view",
            ),
        ),
        migrations.AddConstraint(
            model_name="brandstatusview",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("anonymous_viewer_id__isnull", False), ("user__isnull", True)
                ),
                fields=("status", "anonymous_viewer_id"),
                name="unique_brand_status_anon_view",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                fields=("cart", "product", "specification_signature"),
                name="unique_cart_product_specification",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["customer_user", "issued_at"],
                name="api_invoice_custome_bc2ec0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["document_type", "status", "issued_at"],
                name="api_invoice_documen_c27b68_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="orderchat",
            index=models.Index(
                fields=["status", "last_message_at"],
                name="api_orderch_status_600fd7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="orderchat",
            index=models.Index(
                fields=["assigned_admin", "status"],
                name="api_orderch_assigne_085d7b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="orderchat",
            index=models.Index(
                fields=["customer_user", "status"],
                name="api_orderch_custome_0371c2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="orderchatmessage",
            index=models.Index(
                fields=["chat", "created_at"], name="api_orderch_chat_id_057cff_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="orderchatmessage",
            constraint=models.UniqueConstraint(
                fields=("chat", "sender", "client_message_id"),
                name="unique_order_chat_sender_message",
            ),
        ),
        migrations.AddIndex(
            model_name="orderchatparticipant",
            index=models.Index(
                fields=["user", "chat"], name="api_orderch_user_id_9d2f3f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="orderchatparticipant",
            constraint=models.UniqueConstraint(
                fields=("chat", "user"), name="unique_order_chat_participant"
            ),
        ),
        migrations.AddIndex(
            model_name="productbookmark",
            index=models.Index(
                fields=["product", "created_at"], name="api_product_product_4d6127_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productbookmark",
            index=models.Index(
                fields=["user", "created_at"], name="api_product_user_id_a4c761_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="productbookmark",
            constraint=models.UniqueConstraint(
                fields=("user", "product"), name="unique_product_bookmark"
            ),
        ),
        migrations.AddIndex(
            model_name="storefollow",
            index=models.Index(
                fields=["trader", "created_at"], name="api_storefo_trader__331967_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storefollow",
            index=models.Index(
                fields=["user", "created_at"], name="api_storefo_user_id_c45371_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storefollow",
            index=models.Index(
                fields=["session_key", "created_at"],
                name="api_storefo_session_dabc4b_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="storefollow",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("user", "trader"),
                name="unique_user_store_follow",
            ),
        ),
        migrations.AddConstraint(
            model_name="storefollow",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("user__isnull", True), models.Q(("session_key", ""), _negated=True)
                ),
                fields=("session_key", "trader"),
                name="unique_anonymous_store_follow",
            ),
        ),
        migrations.AddConstraint(
            model_name="storefollow",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("user__isnull", False), ("session_key", "")),
                    models.Q(
                        ("user__isnull", True),
                        models.Q(("session_key", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="store_follow_exactly_one_identity",
            ),
        ),
        migrations.AddIndex(
            model_name="usernotification",
            index=models.Index(
                fields=["recipient", "lifecycle_state", "created_at"],
                name="api_usernot_recipie_50c2f4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usernotification",
            index=models.Index(
                fields=["recipient", "is_read"], name="api_usernot_recipie_fab94d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usernotification",
            index=models.Index(fields=["order"], name="api_usernot_order_i_8a10bf_idx"),
        ),
        migrations.AddIndex(
            model_name="usernotification",
            index=models.Index(
                fields=["product"], name="api_usernot_product_ffc7f5_idx"
            ),
        ),
    ]
