"use client";
import { apiGet, apiPost } from "@/lib/api/client";
import type { AdminChatSummary, AdminRealtimeEvent } from "@/providers/AdminRealtimeProvider";
import { useAdminRealtime } from "@/providers/AdminRealtimeProvider";
import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState, use } from "react";

type Message = { id: number; sender_role: "customer" | "admin" | "system"; sender_name: string; body: string; client_message_id: string; created_at: string };
export default function AdminChatPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params); const chatId = Number(id); const { subscribe, refreshChats } = useAdminRealtime();
  const [chat, setChat] = useState<AdminChatSummary | null>(null); const [messages, setMessages] = useState<Message[]>([]); const [body, setBody] = useState(""); const [busy, setBusy] = useState(false);
  const recover = useCallback(async () => { const [summary, history] = await Promise.all([apiGet<AdminChatSummary>(`/order-chats/${chatId}/`), apiGet<{ results: Message[] }>(`/order-chats/${chatId}/messages/`)]); setChat(summary); setMessages(history.results); }, [chatId]);
  useEffect(() => { void recover(); return subscribe((event: AdminRealtimeEvent) => { if (event.chat_id !== chatId) return; if (event.type === "chat.message.created") { const message = event.message as Message; setMessages((current) => current.some((item) => item.client_message_id === message.client_message_id) ? current : [...current, message]); } else void recover(); }); }, [chatId, recover, subscribe]);
  async function join() { setBusy(true); setChat(await apiPost(`/order-chats/${chatId}/join/`, {})); await refreshChats(); setBusy(false); }
  async function close() { if (!confirm("Close this order chat?")) return; setBusy(true); setChat(await apiPost(`/order-chats/${chatId}/close/`, { reason: "" })); await refreshChats(); setBusy(false); }
  async function send(event: FormEvent) { event.preventDefault(); if (!body.trim()) return; setBusy(true); const message = await apiPost<Message>(`/order-chats/${chatId}/messages/`, { body, client_message_id: crypto.randomUUID() }); setMessages((current) => current.some((item) => item.id === message.id) ? current : [...current, message]); setBody(""); setBusy(false); }
  if (!chat) return <p>Loading chat…</p>;
  return <div className="flex min-h-[75vh] flex-col rounded-[10px] bg-white shadow-1 dark:bg-gray-dark"><header className="flex items-center justify-between border-b p-5 dark:border-dark-3"><div><h1 className="text-xl font-bold text-dark dark:text-white">{chat.order_number}</h1><p className="text-sm text-dark-5">{chat.customer_name} · {chat.customer_phone} · <span className="capitalize">{chat.status}</span></p></div><div className="flex gap-2"><Link href={`/orders/${chat.order}`} className="rounded-lg border px-4 py-2 text-sm font-medium">Order</Link>{chat.status === "requested" ? <button disabled={busy} onClick={join} className="rounded-lg bg-primary px-4 py-2 text-sm font-medium text-white">Join chat</button> : null}{chat.status === "open" ? <button disabled={busy} onClick={close} className="rounded-lg bg-dark px-4 py-2 text-sm font-medium text-white">Close chat</button> : null}</div></header><main className="flex-1 space-y-3 overflow-y-auto p-5">{messages.map((message) => <div key={message.client_message_id} className={`flex ${message.sender_role === "admin" ? "justify-end" : "justify-start"}`}><div className={`max-w-[75%] rounded-2xl px-4 py-2 ${message.sender_role === "admin" ? "bg-dark text-white" : "bg-gray-2 text-dark"}`}><p>{message.body}</p><time className="text-xs opacity-60">{new Date(message.created_at).toLocaleTimeString()}</time></div></div>)}</main>{chat.status !== "closed" ? <form onSubmit={send} className="flex gap-2 border-t p-4 dark:border-dark-3"><textarea maxLength={2000} value={body} onChange={(event) => setBody(event.target.value)} className="min-h-12 flex-1 rounded-lg border p-3 text-dark" placeholder="Reply to customer" /><button disabled={busy || !body.trim()} className="rounded-lg bg-primary px-5 font-medium text-white">Send</button></form> : <p className="border-t p-5 text-center text-dark-5">This chat is closed.</p>}</div>;
}
