"use client";
/* eslint-disable react/jsx-key -- DataTable supplies stable table-cell keys for render arrays. */

import { useEffect, useState } from "react";
import { toast } from "sonner";
import { apiGet } from "@/lib/api/client";
import type { AdminActivityLog, SystemRequestLog, UserActivityLog } from "@/types/logs";
import { DataTable } from "./DataTable";
import { PageHeader } from "./PageHeader";
import { StatCard } from "./StatCard";
import { StatusBadge } from "./StatusBadge";

const input = "w-full rounded-lg border-[1.5px] border-stroke bg-transparent px-4 py-3 text-dark outline-none focus:border-primary dark:border-dark-3 dark:bg-dark-2 dark:text-white";
const card = "rounded-[10px] bg-white p-5 shadow-1 dark:bg-gray-dark dark:shadow-card";
const errorMessage = (error: unknown) => error instanceof Error ? error.message : "Request failed.";
const compact = (value: unknown, max = 80) => { const text = typeof value === "string" ? value : JSON.stringify(value || {}); return text.length > max ? `${text.slice(0, max)}...` : text; };

function DetailModal({ title, value, onClose }: { title: string; value: unknown; onClose: () => void }) {
  return <div className="fixed inset-0 z-99999 flex items-center justify-center bg-black/40 p-4"><div className="max-h-[80vh] w-full max-w-2xl overflow-auto rounded-[10px] bg-white p-5 shadow-1 dark:bg-gray-dark"><div className="mb-4 flex items-center justify-between gap-4"><h2 className="text-lg font-semibold text-dark dark:text-white">{title}</h2><button className="rounded-[5px] border border-stroke px-4 py-2" onClick={onClose}>Close</button></div><pre className="whitespace-pre-wrap rounded-lg bg-gray-1 p-4 text-sm dark:bg-dark-2">{typeof value === "string" ? value : JSON.stringify(value, null, 2)}</pre></div></div>;
}

export function UserActivityLogsPage() {
  const [items, setItems] = useState<UserActivityLog[]>([]);
  const [loading, setLoading] = useState(true);
  const [details, setDetails] = useState<unknown>(null);
  const [filters, setFilters] = useState({ search: "", action: "", product: "", date_from: "", date_to: "" });
  const set = (key: keyof typeof filters, value: string) => setFilters(current => ({ ...current, [key]: value }));
  const load = async () => { setLoading(true); try { const params = new URLSearchParams(); Object.entries(filters).forEach(([key, value]) => value && params.set(key, value)); setItems(await apiGet<UserActivityLog[]>(`/logs/user-activity/?${params}`)); } catch (error) { toast.error(errorMessage(error)); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  return <><PageHeader title="User Activity Logs" description="Track product interactions for future storefront and recommendation features." /><div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Total events" value={items.length} /><StatCard label="Product views" value={items.filter(item => item.action === "product_view").length} /><StatCard label="Cart actions" value={items.filter(item => item.action.includes("cart")).length} /><StatCard label="Ratings" value={items.filter(item => item.action === "rating").length} /></div><div className={`${card} mb-6 grid gap-3 lg:grid-cols-6`}><input className={input} value={filters.search} onChange={e => set("search", e.target.value)} placeholder="Search user, session, product" /><input className={input} value={filters.action} onChange={e => set("action", e.target.value)} placeholder="Action" /><input className={input} value={filters.product} onChange={e => set("product", e.target.value)} placeholder="Product ID" /><input className={input} type="date" value={filters.date_from} onChange={e => set("date_from", e.target.value)} /><input className={input} type="date" value={filters.date_to} onChange={e => set("date_to", e.target.value)} /><button className="rounded-[5px] bg-primary px-5 py-3 font-medium text-white" onClick={() => void load()}>Filter</button></div><DataTable columns={["Time", "User / Session", "Action", "Product", "Rating", "IP", "Device", "Metadata"]} rows={items} empty={loading ? "Loading logs..." : "No activity logs found."} render={item => [new Date(item.created_at).toLocaleString(), item.username_snapshot || item.session_key || "-", <StatusBadge value={item.action} />, item.product_name || item.product || "-", item.rating_value || "-", item.ip_address || "-", `${item.device_type || "-"} / ${item.browser || "-"}`, <button className="text-primary hover:underline" onClick={() => setDetails(item.metadata)}>{compact(item.metadata)}</button>]}/>{details !== null && <DetailModal title="Metadata" value={details} onClose={() => setDetails(null)} />}</>;
}

export function AdminActivityLogsPage() {
  const [items, setItems] = useState<AdminActivityLog[]>([]);
  const [loading, setLoading] = useState(true);
  const [details, setDetails] = useState<unknown>(null);
  const [filters, setFilters] = useState({ search: "", actor: "", module: "", action: "", date_from: "", date_to: "" });
  const set = (key: keyof typeof filters, value: string) => setFilters(current => ({ ...current, [key]: value }));
  const load = async () => { setLoading(true); try { const params = new URLSearchParams(); Object.entries(filters).forEach(([key, value]) => value && params.set(key, value)); setItems(await apiGet<AdminActivityLog[]>(`/logs/admin-activity/?${params}`)); } catch (error) { toast.error(errorMessage(error)); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  return <><PageHeader title="Admin Activity Logs" description="Review admin changes and operational actions." /><div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Total actions" value={items.length} /><StatCard label="Catalog" value={items.filter(item => item.module === "catalog").length} /><StatCard label="Orders" value={items.filter(item => item.module === "orders").length} /><StatCard label="Users" value={items.filter(item => item.module === "users").length} /></div><div className={`${card} mb-6 grid gap-3 lg:grid-cols-7`}><input className={input} value={filters.search} onChange={e => set("search", e.target.value)} placeholder="Search admin, object, IP" /><input className={input} value={filters.actor} onChange={e => set("actor", e.target.value)} placeholder="Actor ID" /><input className={input} value={filters.module} onChange={e => set("module", e.target.value)} placeholder="Module" /><input className={input} value={filters.action} onChange={e => set("action", e.target.value)} placeholder="Action" /><input className={input} type="date" value={filters.date_from} onChange={e => set("date_from", e.target.value)} /><input className={input} type="date" value={filters.date_to} onChange={e => set("date_to", e.target.value)} /><button className="rounded-[5px] bg-primary px-5 py-3 font-medium text-white" onClick={() => void load()}>Filter</button></div><DataTable columns={["Time", "Admin", "Module", "Action", "Object", "IP", "Device", "Status"]} rows={items} empty={loading ? "Loading logs..." : "No admin activity logs found."} render={item => [new Date(item.created_at).toLocaleString(), item.actor_username || "-", item.module, <StatusBadge value={item.action} />, <button className="text-left text-primary hover:underline" onClick={() => setDetails({ object: item.object_repr, metadata: item.metadata })}>{item.object_repr || `${item.object_type} ${item.object_id}` || "-"}</button>, item.ip_address || "-", `${item.device_type || "-"} / ${item.browser || "-"}`, item.status_code || "-"]}/>{details !== null && <DetailModal title="Activity details" value={details} onClose={() => setDetails(null)} />}</>;
}

export function SystemRequestLogsPage() {
  const [items, setItems] = useState<SystemRequestLog[]>([]);
  const [loading, setLoading] = useState(true);
  const [details, setDetails] = useState<unknown>(null);
  const [filters, setFilters] = useState({ search: "", method: "", status_code: "", is_error: "", date_from: "", date_to: "" });
  const set = (key: keyof typeof filters, value: string) => setFilters(current => ({ ...current, [key]: value }));
  const load = async () => { setLoading(true); try { const params = new URLSearchParams(); Object.entries(filters).forEach(([key, value]) => value && params.set(key, value)); setItems(await apiGet<SystemRequestLog[]>(`/logs/system/?${params}`)); } catch (error) { toast.error(errorMessage(error)); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  return <><PageHeader title="System Logs" description="Inspect API request access, device details, duration, and errors." /><div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Total requests" value={items.length} /><StatCard label="Errors" value={items.filter(item => item.is_error).length} /><StatCard label="GET" value={items.filter(item => item.method === "GET").length} /><StatCard label="POST/PATCH" value={items.filter(item => ["POST", "PATCH"].includes(item.method)).length} /></div><div className={`${card} mb-6 grid gap-3 lg:grid-cols-7`}><input className={input} value={filters.search} onChange={e => set("search", e.target.value)} placeholder="Search path, user, IP" /><input className={input} value={filters.method} onChange={e => set("method", e.target.value.toUpperCase())} placeholder="Method" /><input className={input} value={filters.status_code} onChange={e => set("status_code", e.target.value)} placeholder="Status" /><select className={input} value={filters.is_error} onChange={e => set("is_error", e.target.value)}><option value="">All</option><option value="true">Errors</option><option value="false">Non-errors</option></select><input className={input} type="date" value={filters.date_from} onChange={e => set("date_from", e.target.value)} /><input className={input} type="date" value={filters.date_to} onChange={e => set("date_to", e.target.value)} /><button className="rounded-[5px] bg-primary px-5 py-3 font-medium text-white" onClick={() => void load()}>Filter</button></div><DataTable columns={["Time", "User", "Method", "Path", "Status", "Duration", "IP", "Device", "Error"]} rows={items} empty={loading ? "Loading logs..." : "No system logs found."} render={item => [new Date(item.created_at).toLocaleString(), item.username_snapshot || "-", <StatusBadge value={item.method} />, <span className="max-w-80 truncate">{item.path}</span>, item.status_code || "-", `${item.duration_ms || 0} ms`, item.ip_address || "-", `${item.device_type || "-"} / ${item.browser || "-"}`, item.error_message ? <button className="text-red hover:underline" onClick={() => setDetails(item.error_message)}>{compact(item.error_message, 50)}</button> : "-"]}/>{details !== null && <DetailModal title="Error details" value={details} onClose={() => setDetails(null)} />}</>;
}
