"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { apiGet, apiPatch, apiPost } from "@/lib/api/client";
import type { TraderAgreement, TraderBranch, TraderDocument, TraderProfile } from "@/types/registration";
import { DataTable } from "./DataTable";
import { DocumentPreviewModal } from "./DocumentPreviewModal";
import { PageHeader } from "./PageHeader";
import { StatCard } from "./StatCard";
import { StatusBadge } from "./StatusBadge";
import { TraderSearchSelect } from "./TraderSearchSelect";

const input = "w-full rounded-lg border-[1.5px] border-stroke bg-transparent px-4 py-3 text-dark outline-none focus:border-primary dark:border-dark-3 dark:bg-dark-2 dark:text-white";
const card = "rounded-[10px] bg-white p-5 shadow-1 dark:bg-gray-dark dark:shadow-card";
const readError = (error: unknown) => error instanceof Error ? error.message : "Request failed.";
const traderLabel = (item: { trader: number; trader_name?: string; trader_code?: string }) => <span>{item.trader_name || `Trader #${item.trader}`} {item.trader_code && <><br /><span className="text-xs text-primary">{item.trader_code}</span></>}</span>;

export function TradersPage() {
  const [traders, setTraders] = useState<TraderProfile[]>([]); const [loading, setLoading] = useState(true); const [search, setSearch] = useState(""); const [status, setStatus] = useState("");
  const load = async () => { setLoading(true); try { const params = new URLSearchParams(); if (search) params.set("search", search); if (status) params.set("status", status); setTraders(await apiGet(`/registration/traders/?${params}`)); } catch (e) { toast.error(readError(e)); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const action = async (id: number, name: string, payload?: unknown) => { try { await apiPatch(`/registration/traders/${id}/${name}/`, payload); toast.success(`Trader ${name}d.`); void load(); } catch (e) { toast.error(readError(e)); } };
  const totals = (key?: string) => key ? traders.filter(t => t.status === key).length : traders.length;
  return <><PageHeader title="Trader Registration" description="Manage companies and individual traders." action={{ href: "/registration/traders/new", label: "Add Trader" }} /><div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Total Traders" value={totals()} /><StatCard label="Pending" value={totals("pending")} /><StatCard label="Approved" value={totals("approved")} /><StatCard label="Suspended" value={totals("suspended")} /></div><div className={`${card} mb-6 flex flex-col gap-3 sm:flex-row`}><input className={input} value={search} onChange={e => setSearch(e.target.value)} placeholder="Search business, trader ID, owner, phone, email, TIN…" /><select className={input} value={status} onChange={e => setStatus(e.target.value)}><option value="">All statuses</option><option value="pending">Pending</option><option value="approved">Approved</option><option value="suspended">Suspended</option></select><button onClick={() => void load()} className="rounded-[5px] bg-primary px-5 py-3 font-medium text-white">Filter</button></div><DataTable columns={["Business / Trader", "Trader ID", "Type", "Owner", "Phone", "Location", "Status", "Verified", "Created", "Actions"]} rows={traders} empty={loading ? "Loading traders…" : "No traders found."} render={t => [<Link className="font-medium text-primary hover:underline" href={`/registration/traders/${t.id}`}>{t.business_name}</Link>, t.trader_code, t.trader_type, t.owner_full_name || "—", t.phone, [t.region, t.district].filter(Boolean).join(", ") || "—", <StatusBadge value={t.status} />, <StatusBadge value={t.is_verified ? "verified" : "unverified"} />, new Date(t.created_at).toLocaleDateString(), <div className="flex flex-wrap gap-2 text-xs"><Link className="text-primary hover:underline" href={`/registration/traders/${t.id}`}>View</Link>{t.status === "pending" && <button className="text-green hover:underline" onClick={() => void action(t.id, "approve")}>Approve</button>}<button className="text-red hover:underline" onClick={() => void action(t.id, "suspend")}>Suspend</button><button className="text-primary hover:underline" onClick={() => void action(t.id, "feature", { is_featured: !t.is_featured })}>{t.is_featured ? "Unfeature" : "Feature"}</button></div>]}/></>;
}

export function TraderFormPage() {
  const router = useRouter(); const [saving, setSaving] = useState(false);
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setSaving(true); try { await apiPost("/registration/traders/", new FormData(event.currentTarget)); toast.success("Trader created."); router.push("/registration/traders"); router.refresh(); } catch (e) { toast.error(readError(e)); } finally { setSaving(false); } };
  const fields = [["business_name", "Business / trader name", true], ["owner_full_name", "Owner full name"], ["registration_number", "Registration number"], ["tin_number", "TIN number"], ["email", "Email", false, "email"], ["phone", "Phone", true], ["alternative_phone", "Alternative phone"], ["country", "Country"], ["region", "Region"], ["district", "District"], ["ward", "Ward"], ["street", "Street"]] as const;
  return <><PageHeader title="Register Trader" description="Create a company or individual trader record." action={{ href: "/registration/traders", label: "Back" }} /><form onSubmit={submit} className={card}><div className="grid gap-5 md:grid-cols-2"><label>Trader type<select required name="trader_type" className={`${input} mt-2`}><option value="company">Company</option><option value="individual">Individual</option></select></label>{fields.map(([name, label, required, type]) => <label key={name}>{label}<input name={name} required={required} type={type || "text"} defaultValue={name === "country" ? "Tanzania" : ""} className={`${input} mt-2`} /></label>)}<label>Logo<input type="file" name="logo" accept="image/*" className={`${input} mt-2`} /></label><label>Cover image<input type="file" name="cover_image" accept="image/*" className={`${input} mt-2`} /></label><label className="md:col-span-2">Address description<textarea name="address_description" className={`${input} mt-2 min-h-24`} /></label><label className="md:col-span-2">Admin note<textarea name="admin_note" className={`${input} mt-2 min-h-24`} /></label></div><div className="mt-6 flex gap-3"><button disabled={saving} className="rounded-[5px] bg-primary px-6 py-3 font-medium text-white disabled:opacity-60">{saving ? "Saving…" : "Create Trader"}</button><Link href="/registration/traders" className="rounded-[5px] border border-stroke px-6 py-3 font-medium dark:border-dark-3">Cancel</Link></div></form></>;
}

type TraderDetail = TraderProfile & { agreement?: TraderAgreement; documents?: TraderDocument[]; branches?: TraderBranch[] };
export function TraderDetailPage({ id }: { id: string }) {
  const [trader, setTrader] = useState<TraderDetail | null>(null); const [preview, setPreview] = useState<{ title: string; url?: string | null; fileName?: string; extension?: string } | null>(null);
  useEffect(() => { void apiGet<TraderDetail>(`/registration/traders/${id}/`).then(setTrader).catch(e => toast.error(readError(e))); }, [id]);
  if (!trader) return <p>Loading trader…</p>;
  return <><PageHeader title={trader.business_name} description={`${trader.trader_type} • ${trader.trader_code}`} action={{ href: "/registration/traders", label: "Back to traders" }} /><p className="-mt-4 mb-6 text-sm font-medium text-primary">{trader.trader_code}</p><div className="grid gap-6 xl:grid-cols-2"><section className={card}><h2 className="mb-4 text-lg font-semibold text-dark dark:text-white">Profile</h2><dl className="grid grid-cols-2 gap-4 text-sm"><dt>Owner</dt><dd>{trader.owner_full_name || "—"}</dd><dt>Phone</dt><dd>{trader.phone}</dd><dt>Email</dt><dd>{trader.email || "—"}</dd><dt>Status</dt><dd><StatusBadge value={trader.status} /></dd><dt>Location</dt><dd>{[trader.region, trader.district].filter(Boolean).join(", ") || "—"}</dd></dl></section><section className={card}><h2 className="mb-4 text-lg font-semibold text-dark dark:text-white">Agreement</h2>{trader.agreement ? <><p>{trader.agreement.title} — <StatusBadge value={trader.agreement.status} /></p>{trader.agreement.agreement_file_url ? <button onClick={() => setPreview({ title: trader.agreement!.title, url: trader.agreement!.agreement_file_url, fileName: trader.agreement!.agreement_file || undefined })} className="mt-3 text-sm text-primary hover:underline">View Agreement File</button> : <p className="mt-3 text-sm">No file uploaded.</p>}</> : <p>No agreement recorded.</p>}</section><section className={card}><h2 className="mb-4 text-lg font-semibold text-dark dark:text-white">Documents</h2>{trader.documents?.length ? trader.documents.map(d => <div key={d.id} className="mb-3 flex items-center justify-between gap-3"><span>{d.title} <StatusBadge value={d.verified ? "verified" : "pending"} /></span><button onClick={() => setPreview({ title: d.title, url: d.file_url || d.file, fileName: d.file_name, extension: d.file_extension })} className="text-sm text-primary hover:underline">Preview</button></div>) : <p>No documents uploaded.</p>}</section><section className={card}><h2 className="mb-4 text-lg font-semibold text-dark dark:text-white">Branches</h2>{trader.branches?.length ? trader.branches.map(b => <p key={b.id} className="mb-2"><span className="font-medium">{b.name}</span> — {[b.region, b.district].filter(Boolean).join(", ")}<br /><span className="text-xs text-primary">{b.trader_name || trader.business_name} · {b.trader_code || trader.trader_code}</span></p>) : <p>No branches registered.</p>}</section><section className={`${card} xl:col-span-2`}><h2 className="mb-2 text-lg font-semibold text-dark dark:text-white">Admin notes</h2><p>{String(trader.admin_note || "No admin notes.")}</p></section></div>{preview && <DocumentPreviewModal open onClose={() => setPreview(null)} title={preview.title} url={preview.url} fileName={preview.fileName} fileExtension={preview.extension} />}</>;
}

export function AgreementsPage() { const [items, setItems] = useState<TraderAgreement[]>([]); const [preview, setPreview] = useState<TraderAgreement | null>(null); const load = () => apiGet<TraderAgreement[]>("/registration/agreements/").then(setItems).catch(e => toast.error(readError(e))); useEffect(() => { void load(); }, []); const action = async (item: TraderAgreement, actionName: string) => { try { await apiPatch(`/registration/agreements/${item.id}/${actionName}/`); toast.success(`Agreement ${actionName}d.`); void load(); } catch (e) { toast.error(readError(e)); } }; return <><PageHeader title="Trader Agreements" description="Manage commercial agreements for traders." action={{ href: "/registration/agreements/new", label: "Add Agreement" }} /><DataTable columns={["Trader", "Title", "Commission", "Dates", "Status", "Signatures", "Actions"]} rows={items} render={a => [traderLabel(a), <span>{a.title}{a.agreement_file_url && <button className="ml-2 text-xs text-primary hover:underline" onClick={() => setPreview(a)}>View file</button>}</span>, `${a.commission_type}: ${a.commission_value}`, `${a.start_date} – ${a.end_date || "Open"}`, <StatusBadge value={a.status} />, `${a.signed_by_trader ? "Trader" : "No trader"} / ${a.signed_by_platform ? "Platform" : "No platform"}`, <div className="flex gap-2"><button className="text-green hover:underline" onClick={() => void action(a, "activate")}>Activate</button><button className="text-red hover:underline" onClick={() => void action(a, "terminate")}>Terminate</button></div>]}/>{preview && <DocumentPreviewModal open onClose={() => setPreview(null)} title={preview.title} url={preview.agreement_file_url} fileName={preview.agreement_file || undefined} />}</>; }
export function AgreementFormPage() { return <ResourceCreateForm title="Add Agreement" description="Create an agreement for a registered trader." endpoint="/registration/agreements/" backHref="/registration/agreements" submitLabel="Create Agreement" fields={[["title", "Title", "text", true], ["commission_value", "Commission value", "number", true], ["start_date", "Start date", "date", true], ["end_date", "End date", "date"], ["agreement_file", "Agreement file", "file"], ["terms", "Terms", "textarea"]]} selects={[["commission_type", "Commission type", "percentage,fixed,none"], ["status", "Status", "draft,active,expired,terminated"]]} checks={[["signed_by_trader", "Signed by trader"], ["signed_by_platform", "Signed by platform"]]} />; }

export function DocumentsPage() { const [items, setItems] = useState<TraderDocument[]>([]); const [preview, setPreview] = useState<TraderDocument | null>(null); const load = () => apiGet<TraderDocument[]>("/registration/documents/").then(setItems).catch(e => toast.error(readError(e))); useEffect(() => { void load(); }, []); const verify = async (item: TraderDocument) => { try { await apiPatch(`/registration/documents/${item.id}/verify/`); toast.success("Document verified."); void load(); } catch (e) { toast.error(readError(e)); } }; return <><PageHeader title="Trader Documents" description="Review documents submitted by traders." action={{ href: "/registration/documents/new", label: "Add Document" }} /><DataTable columns={["Title", "Trader", "Type", "Verified", "Uploaded", "Actions"]} rows={items} render={d => [<button onClick={() => setPreview(d)} className="font-medium text-primary hover:underline">{d.title}</button>, traderLabel(d), d.document_type, <StatusBadge value={d.verified ? "verified" : "pending"} />, new Date(d.uploaded_at).toLocaleDateString(), <div className="flex gap-2"><button onClick={() => setPreview(d)} className="text-primary hover:underline">View</button>{!d.verified && <button className="text-green hover:underline" onClick={() => void verify(d)}>Verify</button>}</div>]}/>{preview && <DocumentPreviewModal open onClose={() => setPreview(null)} title={preview.title} url={preview.file_url || preview.file} fileName={preview.file_name} fileExtension={preview.file_extension} />}</>; }
export function DocumentFormPage() { return <ResourceCreateForm title="Add Document" description="Upload a document for a registered trader." endpoint="/registration/documents/" backHref="/registration/documents" submitLabel="Create Document" fields={[["title", "Title", "text", true], ["file", "File", "file", true]]} selects={[["document_type", "Document type", "business_license,tin_certificate,national_id,agreement,other"]]} />; }
export function BranchesPage() { const [items, setItems] = useState<TraderBranch[]>([]); useEffect(() => { void apiGet<TraderBranch[]>("/registration/branches/").then(setItems).catch(e => toast.error(readError(e))); }, []); return <><PageHeader title="Trader Branches" description="Manage registered trader locations." action={{ href: "/registration/branches/new", label: "Add Branch" }} /><DataTable columns={["Branch", "Trader", "Location", "Phone", "Main", "Active"]} rows={items} render={b => [b.name, traderLabel(b), [b.region, b.district].filter(Boolean).join(", "), b.phone || "—", <StatusBadge value={b.is_main_branch ? "active" : "inactive"} />, <StatusBadge value={b.is_active ? "active" : "inactive"} />]}/></>; }
export function BranchFormPage() { return <ResourceCreateForm title="Add Branch" description="Register a location for a trader." endpoint="/registration/branches/" backHref="/registration/branches" submitLabel="Create Branch" fields={[["name", "Branch name", "text", true], ["region", "Region", "text", true], ["district", "District", "text"], ["phone", "Phone", "text"], ["email", "Email", "email"]]} checks={[["is_main_branch", "Main branch"], ["is_active", "Active"]]} />; }

type Field = [string, string, string, boolean?];
function ResourceCreateForm({ title, description, endpoint, backHref, submitLabel, fields, selects = [], checks = [] }: { title: string; description: string; endpoint: string; backHref: string; submitLabel: string; fields: Field[]; selects?: [string, string, string][]; checks?: [string, string][] }) {
  const router = useRouter(); const [saving, setSaving] = useState(false);
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); if (!form.get("trader")) { toast.error("Select a trader before saving."); return; } setSaving(true); checks.forEach(([name]) => form.set(name, form.has(name) ? "true" : "false")); try { await apiPost(endpoint, form); toast.success("Saved."); router.push(backHref); router.refresh(); } catch (error) { toast.error(readError(error)); } finally { setSaving(false); } };
  return <><PageHeader title={title} description={description} action={{ href: backHref, label: "Back" }} /><form onSubmit={submit} className={card}><div className="grid gap-5 md:grid-cols-2"><TraderSearchSelect name="trader" label="Trader / business" required />{fields.map(([name, label, type, required]) => <label key={name} className={type === "textarea" ? "md:col-span-2" : ""}>{label}{type === "textarea" ? <textarea name={name} className={`${input} mt-2 min-h-24`} /> : <input required={required} name={name} type={type} step={type === "number" ? "0.01" : undefined} className={`${input} mt-2`} />}</label>)}{selects.map(([name, label, options]) => <label key={name}>{label}<select name={name} className={`${input} mt-2`}>{options.split(",").map(option => <option key={option} value={option}>{option.replaceAll("_", " ")}</option>)}</select></label>)}{checks.map(([name, label]) => <label key={name} className="flex items-center gap-2 pt-7"><input name={name} type="checkbox" defaultChecked={name === "is_active"} />{label}</label>)}</div><div className="mt-6 flex gap-3"><button disabled={saving} className="rounded-[5px] bg-primary px-6 py-3 font-medium text-white disabled:opacity-60">{saving ? "Saving…" : submitLabel}</button><Link href={backHref} className="rounded-[5px] border border-stroke px-6 py-3 font-medium dark:border-dark-3">Cancel</Link></div></form></>;
}
