"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { apiGet, apiPatch, apiPost } from "@/lib/api/client";
import { DataTable } from "./DataTable";
import { PageHeader } from "./PageHeader";
import { StatCard } from "./StatCard";
import { StatusBadge } from "./StatusBadge";
import type { TraderAgreement, TraderBranch, TraderDocument, TraderProfile } from "@/types/registration";

const input = "w-full rounded-lg border-[1.5px] border-stroke bg-transparent px-4 py-3 text-dark outline-none focus:border-primary dark:border-dark-3 dark:bg-dark-2 dark:text-white";
const card = "rounded-[10px] bg-white p-5 shadow-1 dark:bg-gray-dark dark:shadow-card";
const readError = (error: unknown) => error instanceof Error ? error.message : "Request failed.";

export function TradersPage() {
  const [traders, setTraders] = useState<TraderProfile[]>([]); const [loading, setLoading] = useState(true); const [search, setSearch] = useState(""); const [status, setStatus] = useState("");
  const load = async () => { setLoading(true); try { const params = new URLSearchParams(); if (search) params.set("search", search); if (status) params.set("status", status); setTraders(await apiGet(`/registration/traders/?${params}`)); } catch (e) { toast.error(readError(e)); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const action = async (id: number, name: string, payload?: unknown) => { try { await apiPatch(`/registration/traders/${id}/${name}/`, payload); toast.success(`Trader ${name}d.`); void load(); } catch (e) { toast.error(readError(e)); } };
  const totals = (key?: string) => key ? traders.filter(t => t.status === key).length : traders.length;
  return <><PageHeader title="Trader Registration" description="Manage companies and individual traders." action={{ href: "/registration/traders/new", label: "Add Trader" }} /><div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Total Traders" value={totals()} /><StatCard label="Pending" value={totals("pending")} /><StatCard label="Approved" value={totals("approved")} /><StatCard label="Suspended" value={totals("suspended")} /></div><div className={`${card} mb-6 flex flex-col gap-3 sm:flex-row`}><input className={input} value={search} onChange={e => setSearch(e.target.value)} placeholder="Search traders" /><select className={input} value={status} onChange={e => setStatus(e.target.value)}><option value="">All statuses</option><option value="pending">Pending</option><option value="approved">Approved</option><option value="suspended">Suspended</option></select><button onClick={() => void load()} className="rounded-[5px] bg-primary px-5 py-3 font-medium text-white">Filter</button></div><DataTable columns={["Business / Trader", "Type", "Owner", "Phone", "Location", "Status", "Verified", "Created", "Actions"]} rows={traders} empty={loading ? "Loading traders…" : undefined} render={t => [<Link className="font-medium text-primary" href={`/registration/traders/${t.id}`}>{t.business_name}</Link>, t.trader_type, t.owner_full_name || "—", t.phone, [t.region, t.district].filter(Boolean).join(", ") || "—", <StatusBadge value={t.status} />, <StatusBadge value={t.is_verified ? "verified" : "unverified"} />, new Date(t.created_at).toLocaleDateString(), <div className="flex flex-wrap gap-2 text-xs"><Link className="text-primary hover:underline" href={`/registration/traders/${t.id}`}>View</Link>{t.status === "pending" && <button className="text-green hover:underline" onClick={() => void action(t.id, "approve")}>Approve</button>}<button className="text-red hover:underline" onClick={() => void action(t.id, "suspend")}>Suspend</button><button className="text-primary hover:underline" onClick={() => void action(t.id, "feature", { is_featured: !t.is_featured })}>{t.is_featured ? "Unfeature" : "Feature"}</button></div>]}/></>;
}

export function TraderFormPage() {
  const [saving, setSaving] = useState(false);
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setSaving(true); const data = new FormData(event.currentTarget); try { await apiPost("/registration/traders/", data); toast.success("Trader created."); window.location.assign("/registration/traders"); } catch (e) { toast.error(readError(e)); } finally { setSaving(false); } };
  const fields = [["business_name", "Business / trader name", true], ["owner_full_name", "Owner full name"], ["registration_number", "Registration number"], ["tin_number", "TIN number"], ["email", "Email", false, "email"], ["phone", "Phone", true], ["alternative_phone", "Alternative phone"], ["country", "Country"], ["region", "Region"], ["district", "District"], ["ward", "Ward"], ["street", "Street"]] as const;
  return <><PageHeader title="Register Trader" description="Create a company or individual trader record." /><form onSubmit={submit} className={card}><div className="grid gap-5 md:grid-cols-2"><label>Trader type<select required name="trader_type" className={`${input} mt-2`}><option value="company">Company</option><option value="individual">Individual</option></select></label>{fields.map(([name, label, required, type]) => <label key={name}>{label}<input name={name} required={required} type={type || "text"} defaultValue={name === "country" ? "Tanzania" : ""} className={`${input} mt-2`} /></label>)}<label>Logo<input type="file" name="logo" accept="image/*" className={`${input} mt-2`} /></label><label>Cover image<input type="file" name="cover_image" accept="image/*" className={`${input} mt-2`} /></label><label className="md:col-span-2">Address description<textarea name="address_description" className={`${input} mt-2 min-h-24`} /></label><label className="md:col-span-2">Admin note<textarea name="admin_note" className={`${input} mt-2 min-h-24`} /></label></div><button disabled={saving} className="mt-6 rounded-[5px] bg-primary px-6 py-3 font-medium text-white disabled:opacity-60">{saving ? "Saving…" : "Create Trader"}</button></form></>;
}

export function TraderDetailPage({ id }: { id: string }) { const [trader, setTrader] = useState<(TraderProfile & { agreement?: TraderAgreement; documents?: TraderDocument[]; branches?: TraderBranch[] }) | null>(null); useEffect(() => { apiGet<TraderProfile & { agreement?: TraderAgreement; documents?: TraderDocument[]; branches?: TraderBranch[] }>(`/registration/traders/${id}/`).then(setTrader).catch(e => toast.error(readError(e))); }, [id]); if (!trader) return <p>Loading trader…</p>; return <><PageHeader title={trader.business_name} description={`${trader.trader_type} • ${trader.slug}`} action={{ href: "/registration/traders", label: "Back to traders" }} /><div className="grid gap-6 xl:grid-cols-2"><section className={card}><h2 className="mb-4 text-lg font-semibold text-dark dark:text-white">Profile</h2><dl className="grid grid-cols-2 gap-4 text-sm"><dt>Owner</dt><dd>{trader.owner_full_name || "—"}</dd><dt>Phone</dt><dd>{trader.phone}</dd><dt>Email</dt><dd>{trader.email || "—"}</dd><dt>Status</dt><dd><StatusBadge value={trader.status} /></dd><dt>Location</dt><dd>{[trader.region, trader.district].filter(Boolean).join(", ") || "—"}</dd></dl></section><section className={card}><h2 className="mb-4 text-lg font-semibold text-dark dark:text-white">Agreement</h2>{trader.agreement ? <p>{trader.agreement.title} — <StatusBadge value={trader.agreement.status} /></p> : <p>No agreement recorded.</p>}</section><section className={card}><h2 className="mb-4 text-lg font-semibold text-dark dark:text-white">Documents</h2>{trader.documents?.length ? trader.documents.map(d => <p key={d.id} className="mb-2">{d.title} <StatusBadge value={d.verified ? "verified" : "pending"} /></p>) : <p>No documents uploaded.</p>}</section><section className={card}><h2 className="mb-4 text-lg font-semibold text-dark dark:text-white">Branches</h2>{trader.branches?.length ? trader.branches.map(b => <p key={b.id} className="mb-2">{b.name} — {b.region}</p>) : <p>No branches registered.</p>}</section><section className={`${card} xl:col-span-2`}><h2 className="mb-2 text-lg font-semibold text-dark dark:text-white">Admin notes</h2><p>{String(trader.admin_note || "No admin notes.")}</p></section></div></>;
}

export function AgreementsPage() { return <ResourcePage<TraderAgreement> title="Trader Agreements" createHref="/registration/agreements/new" endpoint="/registration/agreements/" columns={["Trader", "Title", "Commission", "Dates", "Status", "Signatures", "Actions"]} render={a => [a.trader, a.title, `${a.commission_type}: ${a.commission_value}`, `${a.start_date} – ${a.end_date || "Open"}`, <StatusBadge value={a.status} />, `${a.signed_by_trader ? "Trader" : "No trader"} / ${a.signed_by_platform ? "Platform" : "No platform"}`, <div className="flex gap-2"><button className="text-green hover:underline" onClick={async () => { try { await apiPatch(`/registration/agreements/${a.id}/activate/`); toast.success("Agreement activated."); } catch (e) { toast.error(readError(e)); } }}>Activate</button><button className="text-red hover:underline" onClick={async () => { try { await apiPatch(`/registration/agreements/${a.id}/terminate/`); toast.success("Agreement terminated."); } catch (e) { toast.error(readError(e)); } }}>Terminate</button></div>]}/>; }
export function AgreementFormPage() { return <SimpleForm title="New Agreement" endpoint="/registration/agreements/" fields={["trader:number:Trader ID", "title:Title", "commission_value:number:Commission value", "start_date:date:Start date", "end_date:date:End date", "agreement_file:file:Agreement file", "terms:textarea:Terms"]} selects={["commission_type:Commission type:percentage,fixed,none", "status:Status:draft,active,expired,terminated"]} checks={["signed_by_trader:Signed by trader", "signed_by_platform:Signed by platform"]} />; }
export function DocumentsPage() { return <ResourcePage<TraderDocument> title="Trader Documents" endpoint="/registration/documents/" create={<SimpleFormCompact endpoint="/registration/documents/" fields={["trader:number:Trader ID", "title:Title", "file:file:File"]} selects={["document_type:Document type:business_license,tin_certificate,national_id,agreement,other"]} />} columns={["Title", "Trader", "Type", "Verified", "Uploaded", "Actions"]} render={d => [d.title, d.trader, d.document_type, <StatusBadge value={d.verified ? "verified" : "pending"} />, new Date(d.uploaded_at).toLocaleDateString(), !d.verified && <button className="text-green hover:underline" onClick={async () => { try { await apiPatch(`/registration/documents/${d.id}/verify/`); toast.success("Document verified."); } catch (e) { toast.error(readError(e)); } }}>Verify</button>]}/>; }
export function BranchesPage() { return <ResourcePage<TraderBranch> title="Trader Branches" endpoint="/registration/branches/" create={<SimpleFormCompact endpoint="/registration/branches/" fields={["trader:number:Trader ID", "name:Branch name", "region:Region", "district:District", "phone:Phone", "email:Email"]} checks={["is_main_branch:Main branch", "is_active:Active"]} />} columns={["Branch", "Trader", "Location", "Phone", "Main", "Active"]} render={b => [b.name, b.trader, [b.region, b.district].filter(Boolean).join(", "), b.phone || "—", <StatusBadge value={b.is_main_branch ? "active" : "inactive"} />, <StatusBadge value={b.is_active} />]}/>; }
function ResourcePage<T extends { id: number }>({ title, endpoint, columns, render, createHref, create }: { title: string; endpoint: string; columns: string[]; render: (item: T) => React.ReactNode[]; createHref?: string; create?: React.ReactNode }) { const [items, setItems] = useState<T[]>([]); useEffect(() => { apiGet<T[]>(endpoint).then(setItems).catch(e => toast.error(readError(e))); }, [endpoint]); return <><PageHeader title={title} action={createHref ? { href: createHref, label: "Add New" } : undefined} />{create && <div className="mb-6">{create}</div>}<DataTable columns={columns} rows={items} render={render} empty="No records found." /></>; }
function SimpleForm({ title, endpoint, fields, selects = [], checks = [] }: { title: string; endpoint: string; fields: string[]; selects?: string[]; checks?: string[] }) { return <><PageHeader title={title}/><SimpleFormCompact endpoint={endpoint} fields={fields} selects={selects} checks={checks} large /></>; }
function SimpleFormCompact({ endpoint, fields, selects = [], checks = [], large = false }: { endpoint: string; fields: string[]; selects?: string[]; checks?: string[]; large?: boolean }) { const submit = async (e: React.FormEvent<HTMLFormElement>) => { e.preventDefault(); const form = new FormData(e.currentTarget); checks.forEach(c => form.set(c.split(":")[0], form.has(c.split(":")[0]) ? "true" : "false")); try { await apiPost(endpoint, form); toast.success("Saved."); e.currentTarget.reset(); } catch (error) { toast.error(readError(error)); } }; return <form onSubmit={submit} className={`${card} ${large ? "" : ""}`}><div className="grid gap-4 md:grid-cols-2">{fields.map(item => { const [name, type, label] = item.split(":"); return <label key={name}>{label}<input required={type !== "file"} name={name} type={type} className={`${input} mt-2`} /></label>; })}{selects.map(item => { const [name, label, options] = item.split(":"); return <label key={name}>{label}<select name={name} className={`${input} mt-2`}>{options.split(",").map(o => <option key={o} value={o}>{o}</option>)}</select></label>; })}{checks.map(item => { const [name, label] = item.split(":"); return <label key={name} className="flex items-center gap-2 pt-7"><input name={name} type="checkbox" />{label}</label>; })}</div><button className="mt-5 rounded-[5px] bg-primary px-5 py-3 font-medium text-white">Save</button></form>; }
