"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { apiGet, apiPatch, apiPost, apiPut } from "@/lib/api/client";
import type { AdminUser, Permission, Role } from "@/types/users";
import { DataTable } from "./DataTable";
import { PageHeader } from "./PageHeader";
import { StatusBadge } from "./StatusBadge";

const input = "w-full rounded-lg border-[1.5px] border-stroke bg-transparent px-4 py-3 text-dark outline-none focus:border-primary dark:border-dark-3 dark:bg-dark-2 dark:text-white";
const card = "rounded-[10px] bg-white p-5 shadow-1 dark:bg-gray-dark dark:shadow-card";
const errorMessage = (error: unknown) => error instanceof Error ? error.message : "Request failed.";

export function UsersPage() { const [users, setUsers] = useState<AdminUser[]>([]); const [search, setSearch] = useState(""); const load = async () => { try { setUsers(await apiGet(`/users/?${search ? `search=${encodeURIComponent(search)}` : ""}`)); } catch (e) { toast.error(errorMessage(e)); } }; useEffect(() => { void load(); }, []); const state = async (user: AdminUser, endpoint: string) => { try { await apiPatch(`/users/${user.id}/${endpoint}/`); toast.success("User updated."); void load(); } catch (e) { toast.error(errorMessage(e)); } }; return <><PageHeader title="Users" description="Manage dashboard users and their Django roles." action={{ href: "/user-management/users/new", label: "Add User" }} /><div className={`${card} mb-6 flex gap-3`}><input className={input} placeholder="Search users" value={search} onChange={e => setSearch(e.target.value)} /><button className="rounded-[5px] bg-primary px-5 py-3 font-medium text-white" onClick={() => void load()}>Search</button></div><DataTable columns={["User", "Email", "Status", "Roles", "Staff", "Actions"]} rows={users} render={u => [<Link className="font-medium text-primary" href={`/user-management/users/${u.id}`}>{u.username}</Link>, u.email || "—", <StatusBadge value={u.is_active} />, u.group_details.map(g => g.name).join(", ") || "—", u.is_staff ? "Yes" : "No", <div className="flex gap-2"><Link className="text-primary hover:underline" href={`/user-management/users/${u.id}`}>View</Link><button className="text-red hover:underline" onClick={() => void state(u, u.is_active ? "deactivate" : "activate")}>{u.is_active ? "Deactivate" : "Activate"}</button></div>]}/></>; }
export function NewUserPage() { const [roles, setRoles] = useState<Role[]>([]); useEffect(() => { apiGet<Role[]>("/roles/").then(setRoles).catch(e => toast.error(errorMessage(e))); }, []); const submit = async (e: React.FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); const groups = f.getAll("groups").map(Number); const data = Object.fromEntries(f); try { await apiPost("/users/", { ...data, groups, is_active: f.has("is_active"), is_staff: f.has("is_staff") }); toast.success("User created."); window.location.assign("/user-management/users"); } catch (err) { toast.error(errorMessage(err)); } }; return <><PageHeader title="New User" action={{ href: "/user-management/users", label: "Back" }}/><form onSubmit={submit} className={card}><div className="grid gap-5 md:grid-cols-2">{[["username", "Username", "text"], ["email", "Email", "email"], ["first_name", "First name", "text"], ["last_name", "Last name", "text"], ["password", "Password", "password"]].map(([name, label, type]) => <label key={name}>{label}<input required={name === "username" || name === "password"} name={name} type={type} className={`${input} mt-2`} /></label>)}<fieldset className="md:col-span-2"><legend className="font-medium text-dark dark:text-white">Roles</legend><div className="mt-3 flex flex-wrap gap-4">{roles.map(r => <label key={r.id} className="flex items-center gap-2"><input type="checkbox" name="groups" value={r.id} />{r.name}</label>)}</div></fieldset><label className="flex items-center gap-2"><input defaultChecked type="checkbox" name="is_active"/>Active</label><label className="flex items-center gap-2"><input type="checkbox" name="is_staff"/>Staff access</label></div><button className="mt-6 rounded-[5px] bg-primary px-6 py-3 font-medium text-white">Create User</button></form></>; }
export function UserDetailPage({ id }: { id: string }) { const [user, setUser] = useState<AdminUser | null>(null); const [password, setPassword] = useState(""); const load = () => apiGet<AdminUser>(`/users/${id}/`).then(setUser).catch(e => toast.error(errorMessage(e))); useEffect(() => { void load(); }, [id]); if (!user) return <p>Loading user…</p>; return <><PageHeader title={user.username} description={user.email} action={{ href: "/user-management/users", label: "Back to users" }} /><div className="grid gap-6 xl:grid-cols-2"><section className={card}><h2 className="mb-4 text-lg font-semibold text-dark dark:text-white">Profile</h2><p>{user.first_name} {user.last_name}</p><p className="mt-2">Status: <StatusBadge value={user.is_active}/></p><p className="mt-2">Staff: {user.is_staff ? "Yes" : "No"}</p></section><section className={card}><h2 className="mb-4 text-lg font-semibold text-dark dark:text-white">Assigned roles</h2>{user.group_details.length ? user.group_details.map(r => <p key={r.id}>{r.name}</p>) : <p>No roles assigned.</p>}</section><section className={card}><h2 className="mb-4 text-lg font-semibold text-dark dark:text-white">Direct permissions</h2>{user.permission_details.length ? user.permission_details.map(p => <p key={p.id}>{p.name}</p>) : <p>No direct permissions.</p>}</section><section className={card}><h2 className="mb-4 text-lg font-semibold text-dark dark:text-white">Set password</h2><div className="flex gap-3"><input className={input} type="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="New password"/><button className="rounded-[5px] bg-primary px-5 text-white" onClick={async () => { try { await apiPatch(`/users/${id}/set_password/`, { password }); setPassword(""); toast.success("Password updated."); } catch (e) { toast.error(errorMessage(e)); } }}>Save</button></div></section></div></>; }
export function RolesPage() { const [roles, setRoles] = useState<Role[]>([]); useEffect(() => { apiGet<Role[]>("/roles/").then(setRoles).catch(e => toast.error(errorMessage(e))); }, []); return <><PageHeader title="Roles" description="Roles map to Django groups and define backend permissions." action={{ href: "/user-management/roles/new", label: "Add Role" }}/><DataTable columns={["Role", "Users", "Permissions", "Actions"]} rows={roles} render={r => [r.name, r.user_count, r.permission_details.length, <Link className="text-primary hover:underline" href={`/user-management/roles/${r.id}`}>Edit permissions</Link>]}/></>; }
export function NewRolePage() { return <RoleEditor />; }
export function RoleDetailPage({ id }: { id: string }) { return <RoleEditor id={id} />; }
function RoleEditor({ id }: { id?: string }) { const [role, setRole] = useState<Role | null>(null); const [permissions, setPermissions] = useState<Permission[]>([]); const [name, setName] = useState(""); const [selected, setSelected] = useState<number[]>([]); useEffect(() => { apiGet<Permission[]>("/permissions/").then(setPermissions).catch(e => toast.error(errorMessage(e))); if (id) apiGet<Role>(`/roles/${id}/`).then(r => { setRole(r); setName(r.name); setSelected(r.permissions); }).catch(e => toast.error(errorMessage(e))); }, [id]); const save = async () => { try { const data = { name, permissions: selected }; if (id) await apiPut(`/roles/${id}/`, data); else await apiPost("/roles/", data); toast.success("Role saved."); if (!id) window.location.assign("/user-management/roles"); } catch (e) { toast.error(errorMessage(e)); } }; const grouped = permissions.reduce<Record<string, Permission[]>>((groups, permission) => { const key = `${permission.app_label} / ${permission.model}`; (groups[key] ||= []).push(permission); return groups; }, {}); return <><PageHeader title={role ? `Role: ${role.name}` : "New Role"} action={{ href: "/user-management/roles", label: "Back to roles" }}/><section className={card}><label className="block max-w-lg">Role name<input className={`${input} mt-2`} value={name} onChange={e => setName(e.target.value)} /></label><h2 className="mt-8 text-lg font-semibold text-dark dark:text-white">Permissions</h2><p className="mt-1 text-sm">Permissions are grouped by Django app and model.</p><div className="mt-5 grid gap-5 lg:grid-cols-2">{Object.entries(grouped).map(([group, list]) => <div key={group} className="rounded-lg border border-stroke p-4 dark:border-dark-3"><h3 className="mb-3 font-medium text-dark dark:text-white">{group}</h3>{list.map(p => <label key={p.id} className="mb-2 flex items-start gap-2 text-sm"><input type="checkbox" checked={selected.includes(p.id)} onChange={() => setSelected(current => current.includes(p.id) ? current.filter(value => value !== p.id) : [...current, p.id])}/><span><b>{p.codename}</b><br/>{p.name}</span></label>)}</div>)}</div><button onClick={() => void save()} className="mt-6 rounded-[5px] bg-primary px-6 py-3 font-medium text-white">Save Role</button></section></>; }
export function PermissionsPage() { const [permissions, setPermissions] = useState<Permission[]>([]); useEffect(() => { apiGet<Permission[]>("/permissions/").then(setPermissions).catch(e => toast.error(errorMessage(e))); }, []); return <><PageHeader title="Permissions" description="Read-only Django permission catalogue used by roles."/><DataTable columns={["App", "Model", "Codename", "Name"]} rows={permissions} render={p => [p.app_label, p.model, <code>{p.codename}</code>, p.name]}/></>; }
